- name: Verify OSPF operation
  hosts: ios
  gather_facts: no

  tasks:
    - name: Check OSPF neighbors
      cisco.ios.ios_command:
        commands:
          - show ip ospf neighbor
      register: ospf_neighbor

    - name: Check OSPF interface status
      cisco.ios.ios_command:
        commands:
          - show ip ospf interface g0/0
      register: ospf_interface

    - name: Check OSPF routes
      cisco.ios.ios_command:
        commands:
          - show ip route ospf
      register: ospf_routes




- name: Save OSPF verification output
  copy:
    content: |
      ===== {{ inventory_hostname }} =====

      --- OSPF Neighbor ---
      {{ ospf_neighbor.stdout[0] }}

      --- OSPF Interface ---
      {{ ospf_interface.stdout[0] }}

      --- OSPF Routes ---
      {{ ospf_routes.stdout[0] }}
    dest: outputs/{{ inventory_hostname }}_ospf_verify.txt


